#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MANTISSA_LEN_FLOAT 30
#define MANTISSA_LEN 40
#define ORDER_LEN 5
// #define MAX_LEN_STR 51
#define MAX_LEN_INPUT_STR 51

#define ERROR_INPUT_STRUCT 1
#define ERROR_ADD 2
#define ERROR_INPUT_FIRST 3
#define ERROR_INPUT_SECOND 4
#define ERROR_MUL 5
// #define ERROR_BIG_NUM -1
#define ERROR_OWERFLOW_MANTISSA -1
#define ERROR_OWERFLOW_ORDER -2
#define ERROR_INCORRECT_OPERATION -3
#define ERROR_DIVISION_BY_ZERO -4

#endif
